language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

before_install:
  - composer self-update

install:
  - composer install
  - composer require satooshi/php-coveralls '~1.0'

script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
